# Python for Data Science, Level I
### *Session \#5*
---

### Helpful shortcuts
---

**SHIFT** + **ENTER** ----> Execute Cell

**TAB** ----> See autocomplete options

**ESC** then **b** ----> Create Cell 

**ESC** then **dd** ----> Delete Cell

**\[python expression\]?** ---> Explanation of that Python expression

**ESC** then **m** then __ENTER__ ----> Switch to Markdown mode

## I. Array Basics


### Warm Ups
---

**Import numpy:** `import numpy as np`

In [2]:
import numpy as np

**Create an array from a list:** `int_array = np.array([8, 6, 7, 5, 3, 0, 9])`

**Broadcasting:** `int_array * 3`

**Element-wise arithmetic:** `np.array([1, 2, 3]) + np.array([3, 2, 1])`

### Exercises
---
**1. The array** `temps` **represents a sequence of temperature readings in Farenheit. Use broadcasting to convert them all to Celcius.**

Hint: To convert from Farenheit to Celcius, subtract 32 degress and multiply by 5/9.

In [6]:
temps = np.array([92, 103, 85, 94, 90, 92, 87, 82, 80])

celsius = (temps - 32) * 5/9

**2. Use broadcasting to convert your new temperature array to Kelvin.**

Hint: To convert Celcius to Kelvin, add 273 degrees.

In [7]:
celsius + 273

array([306.33333333, 312.44444444, 302.44444444, 307.44444444,
       305.22222222, 306.33333333, 303.55555556, 300.77777778,
       299.66666667])

**3. Each of the** `game` **arrays represents how many points were scored that game by each player on the team**

**Create an array of each player's average number of points scored, using element-wise arithmetic and broadcasting.**

In [9]:
game1 = np.array([6, 26, 18, 10])
game2 = np.array([12, 24, 28, 8])
game3 = np.array([14, 30, 22, 14])

# ADD YOUR CODE DOWN HERE
(game1 + game2 + game3) / 3

array([10.66666667, 26.66666667, 22.66666667, 10.66666667])

**4. What would the averages look like if each player had scored twice as many points during the last game?**

In [10]:
 (game1 + game2 + game3*2) / 3

array([15.33333333, 36.66666667, 30.        , 15.33333333])

**5. The array** `book_pages` **represents how many pages each book has, and** `book_hours` **represents how long it took to finish the book.**

**Which book was most difficult to read, based on its pages-per-hour reading rate?**

In [14]:
book_pages = np.array([320, 173, 532, 801, 275])
book_hours = np.array([  3,   2,   6,  19,   4])

np.min(book_pages / book_hours)

array([106.66666667,  86.5       ,  88.66666667,  42.15789474,
        68.75      ])

### Extra Credit
---
**1. Numpy also provides handy functions for creating arrays, such as** `np.random.randint()`. **The function takes three inputs: the lower bound, the upper bound, and the number of random numbers you want. For example:**

np.random.randint(1,10, 3) ---> array([1, 3, 9])

**How would you use** `randint()` **to simulate a turn in the game Yahtzee, which is played with 5 standard dice?** 

In [18]:
np.random.randint(1,7,5)

array([4, 1, 4, 5, 4])

## II. Boolean Masks


### Warm Ups
---

**1. Create a boolean mask:** `int_array < 3`

**2. Filtering using a boolean mask:** `int_array[int_array < 3]`

**3. Combining boolean masks with an OR operator:** `int_array[(3 < int_array) | (int_array < 7)]`

**4. Combining boolean masks with an AND operator:** `int_array[(3 < int_array) & (int_array < 7)]`

**5. Assignment using a boolean mask:** `int_array[int_array % 2 == 0] = 0`

### Exercises
---

**1. The array** `test_scores` **represents the final test scores for a class. How many students got at least 80 points on the test?**

In [21]:
test_scores = np.array([68, 95, 92, 73, 84, 90, 69, 75, 80, 82, 90, 85, 86, 64, 98])

len(test_scores[test_scores >= 80])

10

**2. Filter the array to just students who got between 65 and 75 points on the test.**

In [22]:
above_65 = test_scores > 65
below_75 = test_scores < 75

test_scores[above_65 & below_75]

array([68, 73, 69])

**3. How many students got above 95 or below 65 points?**

In [24]:
below_65 = test_scores < 65
above_95 = test_scores > 95

test_scores[below_65 | above_95]

array([64, 98])

**4. How many students got exactly 90 points?**

In [26]:
len(test_scores[test_scores == 90])

2

**5. The array** `golf_scores` **represents how many strokes a golfer took on each hole during a round.**

**There's a 6-stroke maximum, so overwrite any higher score with a 6.** 

Hint: Use a boolean mask to assign the new value.

In [27]:
golf_scores = np.random.randint(1, 10, 18)

array([7, 4, 5, 2, 9, 6, 1, 7, 1, 3, 5, 8, 3, 4, 8, 1, 5, 3])

In [30]:
golf_scores[golf_scores > 6] = 6

array([6, 4, 5, 2, 6, 6, 1, 6, 1, 3, 5, 6, 3, 4, 6, 1, 5, 3])

### Extra Credit
---

**1. Par, or the expected number of strokes, for each hole is given by the array** `par`

**Which holes did the golfer shoot at or under par?**

Hint: First find a boolean mask for the holes under par, then use it on the array `[1, 2, 3, ..., 18]`.

In [33]:
par = np.array([3, 4, 3, 3, 5, 3, 4, 3, 3, 4, 5, 3, 3, 3, 5, 3, 3, 3])

hole_numbers = np.array(range(1, 19))

hole_numbers[golf_scores <= par]

array([ 2,  4,  7,  9, 10, 11, 13, 16, 18])

## III. Array Methods

*Note: All array methods can also be called as functions of the Numpy module.* `int_array.sum()` <=> `np.sum(int_array)`

### Warm Ups
---

**Sum of an array:** `int_array.sum()`

73

**Product of an array:** `int_array.prod()`

**Find the max or min element:** `int_array.max()` **or** `int_array.min()`

**Find the average:** `int_array.mean()`

4.055555555555555

**Sort an array:** `int_array.sort()`

## Exercises
---
**1. Find the average test score from** `test_scores`

In [43]:
avg = test_scores.mean()
avg

82.06666666666666

**2. Create an array showing how many points above/below average each test score was.**

In [41]:
test_scores - avg

[68 95 92 73 84 90 69 75 80 82 90 85 86 64 98]


array([-14.06666667,  12.93333333,   9.93333333,  -9.06666667,
         1.93333333,   7.93333333, -13.06666667,  -7.06666667,
        -2.06666667,  -0.06666667,   7.93333333,   2.93333333,
         3.93333333, -18.06666667,  15.93333333])

**3. Find the final number of strokes over par, by summing** `golf_scores` **and** `par`

In [46]:
golf_scores.sum() - par.sum()

10

**4. Find the number of degrees between the coldest and hottest temperature readings from** `temps` 

In [47]:
temps.max() - temps.min()

23

### Extra Credit
---

**1. Among students who scored higher than 70 points in** `test_scores`, **what was the average score?** 

In [49]:
test_scores[test_scores > 70].mean()

85.83333333333333

**2. If you removed the worst three scores from** `test_scores`, **what would be the average score?**

In [54]:
test_scores.sort()
test_scores[3:].mean()

85.83333333333333